name: VOItute
channels:
  - conda-forge
  - defaults
dependencies:
  - cmdstanpy=1.2.5
  - highspy=1.10.0
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - linopy=0.5.3
  - matplotlib=3.10.0
  - numpy=1.26.4
  - pandas=2.2.3
  - pip=25.0
  - python=3.10
  - seaborn=0.13.2
  - tabulate=0.9.0
  - pip:
    - gurobipy=12.0.1